tasks:
  - name: Install dependencies
    init: yarn install
    command: gp sync-done ready

  - name: Bundle and serve
    command: >-
        gp sync-await ready &&
        ./node_modules/.bin/parcel watch index.html & 
        ./node_modules/.bin/browser-sync start -s 'dist' -w --no-ui --no-open &
  
  - name: Test
    command: gp sync-await ready && ./node_modules/.bin/jest --watch

ports:
  - port: 3000
    onOpen: open-preview
